### ISSUE TITLE
Inflating View Exception

### ISSUE THREAD

**Issue by NikNoori** [ImangazalievM/CircleMenu#37]
`Unable to start activity ComponentInfo{com.app.hiitdeckofcards/com.app.hiitdeckofcards.ui.bottomnavigation.BottomNavigationActivity}: android.view.InflateException: Binary XML file line #41 in com.app.hiitdeckofcards:layout/activity_bottom_navigation: Binary XML file line #339 in com.app.hiitdeckofcards:layout/fragment_home: Binary XML file line #339 in com.app.hiitdeckofcards:layout/fragment_home: Error inflating class com.imangazaliev.circlemenu.CircleMenu
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)`

Getting above issue and App crashes.

**Comment by KeQian** [comment]
遇到了相同的问题,这是我的代码，加载的时候直接报错



```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/kernel_window_bg_gray_F6F7FA"
    tools:ignore="ResourceName">


    <androidx.recyclerview.widget.RecyclerView
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:id="@+id/rcv_content"
        android:layout_width="0dp"
        android:layout_height="wrap_content" />



    <com.imangazaliev.circlemenu.CircleMenu
        android:id="@+id/circleMenu"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginTop="60dp"
        android:layout_marginEnd="8dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|bottom"
        android:layout_margin="16dp"
        app:buttonIcons="@array/profile_menu_icons"
        app:distance="120dp"
        app:iconsColor="?colorAccent"
        app:centerButtonColor="?colorAccent"
        app:centerButtonIconColor="#ffffff"
        app:maxAngle="140"
        app:menuIcon="plus"
        app:showSelectAnimation="false"
        app:startAngle="-180"
       />


</FrameLayout>
```

Error inflating class com.imangazaliev.circlemenu.CircleMenu
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:864)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)

**Comment by KeQian** [comment]
Error inflating class com.imangazaliev.circlemenu.CircleMenu
                                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                                        	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                        	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                        	at android.view.LayoutInflater.createView(LayoutInflater.java:864)
                                                                                        	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
                                                                                        	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
                                                                                        	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
                                                                                        	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
